### ISSUE TITLE
ValueError: window shape cannot be larger than input array shape

### ISSUE THREAD

**Issue by long21wt** [ChenghaoMou/embeddings#2]
Hi,
Thanks for your work

I tried to fine tune Bert using your tokenizer API and mapping it to huggingface dataset mnli. But I got this issue:
```
Traceback (most recent call last):
  File "/mnt/beegfs/work/vu/works/bert-tokenize/finetune_bert.py", line 27, in <module>
    tokenized_datasets = dataset.map(tokenization, batched=True)
  File "/storage/ukp/work/vu/miniconda/envs/token-reload/lib/python3.10/site-packages/datasets/dataset_dict.py", line 770, in map
    {
  File "/storage/ukp/work/vu/miniconda/envs/token-reload/lib/python3.10/site-packages/datasets/dataset_dict.py", line 771, in <dictcomp>
    k: dataset.map(
  File "/storage/ukp/work/vu/miniconda/envs/token-reload/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 2376, in map
    return self._map_single(
  File "/storage/ukp/work/vu/miniconda/envs/token-reload/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 551, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/storage/ukp/work/vu/miniconda/envs/token-reload/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 518, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/storage/ukp/work/vu/miniconda/envs/token-reload/lib/python3.10/site-packages/datasets/fingerprint.py", line 458, in wrapper
    out = func(self, *args, **kwargs)
  File "/storage/ukp/work/vu/miniconda/envs/token-reload/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 2764, in _map_single
    batch = apply_function_on_filtered_inputs(
  File "/storage/ukp/work/vu/miniconda/envs/token-reload/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 2644, in apply_function_on_filtered_inputs
    processed_inputs = function(*fn_args, *additional_args, **fn_kwargs)
  File "/storage/ukp/work/vu/miniconda/envs/token-reload/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 2336, in decorated
    result = f(decorated_item, *args, **kwargs)
  File "/mnt/beegfs/work/vu/works/bert-tokenize/finetune_bert.py", line 18, in tokenization
    return tokenizer(
  File "/storage/ukp/work/vu/miniconda/envs/token-reload/lib/python3.10/site-packages/text_embeddings/base/__init__.py", line 139, in __call__
    second_embeddings = self.text2embeddings(second_text)
  File "/storage/ukp/work/vu/miniconda/envs/token-reload/lib/python3.10/site-packages/text_embeddings/visual/vtr.py", line 119, in text2embeddings
    sliding_window_view(image_array, (image_array.shape[0], self.window_size)),
  File "<__array_function__ internals>", line 180, in sliding_window_view
  File "/storage/ukp/work/vu/miniconda/envs/token-reload/lib/python3.10/site-packages/numpy/lib/stride_tricks.py", line 332, in sliding_window_view
    raise ValueError(
ValueError: window shape cannot be larger than input array shape
```
Here is my code snippet:
```python
from text_embeddings.visual import VTRTokenizer
from transformers import BertForSequenceClassification

tokenizer = VTRTokenizer(
    font="/storage/ukp/work/vu/works/bert-tokenize/NotoSans-Regular.ttf",
)

model = BertForSequenceClassification.from_pretrained('bert-base-uncased', num_labels=3)

def tokenization(example):
    return tokenizer(
        example["premise"], 
        example["hypothesis"],
        padding="longest",
        truncation="longest_first",
    )

dataset = load_dataset('multi_nli')

tokenized_datasets = dataset.map(tokenization, batched=True)
```
Do you have any workaround to fix it ?
Thanks

**Comment by ChenghaoMou** [comment]
Hi, thanks for the feedback!

I uploaded a quick fix for the issue. It should work with your code now. 

But I couldn't help wondering if fine-tuning a pre-trained model with this would work at all. For starters, a pre-trained model's weights are all trained based on the input embedding layer. By using a `VTRTokenizer`, you will be feeding embeddings into the model instead of one-hot encodings. It won't be compatible unless you modify the model architecture. Even then, it will be equivalent to training the model from scratch.

You might be interested in fine-tuning models like this [[2207.06991] Language Modelling with Pixels](https://arxiv.org/abs/2207.06991) directly.

**Comment by long21wt** [comment]
Thank you, I definitely look into it.
